name: note_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # المكتبات الأساسية لـ Hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # أدوات توليد الكود (تأكد من وجود hive_generator)
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  chopper_generator: ^8.0.0

flutter:
  uses-material-design: true

  # تعريف الخطوط (تأكد من صحة مسار الملف في مشروعك)
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/views/widgets/assets/Poppins-Regular.ttf